name: workflow with github actions
'on':
  push:
    branches:
      - main
      - dev
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install
        run: npm install
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: ansible-lint
        uses: ansible/ansible-lint-action@v4.1.0.post0
